#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASSETS_DIR="$SCRIPT_DIR/../lib/pixils/assets"
OUT_DIR="$SCRIPT_DIR/../lib/pixils/src/asset"

mkdir -p "$OUT_DIR"

python3 - "$ASSETS_DIR" "$OUT_DIR" << 'EOF'
import sys
import os

assets_dir, out_dir = sys.argv[1], sys.argv[2]

assets = [
    ("consolefont.png", "consolefont_png"),
    ("pixils_logo.png", "pixils_logo_png"),
]

for png_name, symbol in assets:
    png_path = os.path.join(assets_dir, png_name)
    out_path = os.path.join(out_dir, symbol + ".cpp")

    with open(png_path, "rb") as f:
        data = f.read()

    cols = 12
    rows = [data[i:i+cols] for i in range(0, len(data), cols)]
    hex_lines = ",\n".join(
        "  " + ", ".join(f"0x{b:02x}" for b in row)
        for row in rows
    )

    cpp = f"""\
// Generated by scripts/generate_assets.sh - do not edit manually.
// To regenerate: run scripts/generate_assets.sh from the repo root.
// Source asset: lib/pixils/assets/{png_name}

#include <pixils/asset/embedded_assets.h>

namespace Pixils::Assets
{{

// clang-format off
static const unsigned char {symbol}_data[] = {{
{hex_lines}
}};
// clang-format on

const EmbeddedAsset {symbol} = {{ {symbol}_data, sizeof({symbol}_data) }};

}} // namespace Pixils::Assets
"""

    with open(out_path, "w") as f:
        f.write(cpp)

    print(f"Generated: {out_path} ({len(data)} bytes)")
EOF
